### ISSUE TITLE
Fix bug "MC-194811" (Missing structures will destroy saved worlds)

### ISSUE THREAD

**Issue by marios-andr** [alcatrazEscapee/Chocolate#4]
This is a really annoying bug that has to do with world gen so I thought I'd ask, is it possible for you to fix this bug: [MC-194811](https://bugs.mojang.com/browse/MC-194811) ? Am not sure what you will need to do to fix this but if you could take a look i'd appreciate it. Cheers!

**Comment by alcatrazEscapee** [comment]
I'd heard of this before, however I was under the impression it was already fixed by Forge - but that may not be the case (?). Or it may just be sitting in a PR getting stale.

Fabric API had fixed this a while ago although.

Edit:
This is currently PR'd to Forge in https://github.com/MinecraftForge/MinecraftForge/pull/7471. If for some reason is it not possible to fix it in Forge itself, I would consider implementing the same fix into Chocolate.

**Comment by alcatrazEscapee** [comment]
This has now been fixed in Forge, as of 1.16.4-35.0.22, and as such is not needed by Chocolate.
