### ISSUE TITLE
Performance issues with AMD GPU's? Or Systems?

### ISSUE THREAD

**Issue by Explode007** [alcatrazEscapee/Chocolate#7]
So my build is completely AMD, never had issue running anything until I found out that mods alike to foamfix cause issues and so same thing happening here. I Don't know if it's something that's solvable or it just exists, but I wanted to inform it regardless. Only fix I've found is not using it, but now its a requirement for BYG.

**Comment by alcatrazEscapee** [comment]
BYG requires it due to the problems that arise from [MC-202036](https://bugs.mojang.com/browse/MC-202036) have bitten them (or more clearly, their users) in the rear when BYG adds / removes biomes. But that aside, what even is the issue? I have not noticed any significant performance concerns, neither do I think this would make *any* difference on different system architectures.

> mods alike to foamfix

Which this is not in the slightest. Foamfix deduplicates model and blockstates in memory. Chocolate modifies biome serialization and de-serialization and saves additional data to chunks. There's nothing to compare between the two.

I'm fairly confident you may be experiencing an actual issue but are misdiagnosing it. In any case, there's literally nothing I can do with this level of issue report. At the very least for a performance concern I would need to see logs and a profiler result showing the issue as I've said - I cannot reproduce.
